name: Build and Push ARM Docker Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: eduardvalentin/eea-website-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Print DockerHub Username (Sanity Check)
        run: echo "DockerHub Username: ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Debug Login to DockerHub
        run: |
          echo "Attempting Docker login..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || exit 1
          echo "✅ Docker login successful!"

      - name: Debug DockerHub Access (Check Repo Exists)
        run: |
          echo "Checking repository access..."
          curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/plone-backend/"

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3        

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Determine Docker tag
      #   id: vars
      #   run: |
      #     VERSION=${GITHUB_REF#refs/tags/}
      #     echo "version=$VERSION" >> $GITHUB_ENV

      # - name: Build and push Docker image (ARM)
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/arm64
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.version }}
      #       ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
      #     no-cache: true
